version: 0.1.0
editor: claude-code
local:
  patterns:
    - "**/*.ctx.md"
    - "**/ctx.md"
  ignore:
    - node_modules/**
    - dist/**
    - build/**
    - .git/**
global:
  directory: ctx
  patterns: "**/*.md"
  ignore:
    - templates/**
    - README.md
    - "*-context-registry.yml"
    - issues/**
work:
  directory: .worktrees # automatically added to .gitignore
  issue_store:
    type: local # local | github-issue | linear
    # url: https://github.com/{owner}/{repo}/issues  # required for github-issue
    # url: https://linear.app/{workspace}  # required for linear
    # project_id: PROJECT_ID  # required for linear
frontmatter:
  local: optional
  global: optional
